<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AddressesRepository extends EntityRepository
{
}
