<?php

namespace ShopBundle\Repository;

/**
 * CustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOrdersWithAC($hash)
    {
        $products = $this->createQueryBuilder("o")
            ->innerJoin('o.addressId', 'a')
            ->innerJoin('o.products', 'p')
            ->where('o.hash = :hash')->setParameter('hash', $hash);

    }


}

