<?php

namespace ShopBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOrdersWithAC($hash)
    {
        $products = $this->createQueryBuilder("o")
            ->innerJoin('o.addressId', 'a')
            ->innerJoin('o.products', 'p')
            ->innerJoin('o.customerId', 'c')
            ->where('o.hash = :hash')->setParameter('hash', $hash)->getQuery()->getResult();
        return $products;


    }

    public function findUserOrdersAC($user)
    {
        $qb = $this->createQueryBuilder("o")
            ->innerJoin('o.addressId', 'a')
            ->innerJoin('o.products', 'p')
            ->innerJoin('o.customerId', 'c')
            ->where('c.user = :user')
            ->setParameter('user', $user)
            ->getQuery()->getResult();
        return $qb;
    }

    public function findUserOrders($user)
    {

        return $qb2 = $this->createQueryBuilder('p')
            ->innerJoin('p.customerId', 'c')
            ->where('c.user = :user')
            ->setParameter('user', $user)
            ->select('p')
            ->getQuery()
            ->getResult();

    }


}

