<?php

namespace ShopBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{


    public function findActivePromotions()
    {
        return $this->createQueryBuilder('p')
            ->where(':datenow  >= p.dateFrom')->andWhere(':date2 <= p.dateTo')
            ->setParameter('datenow', date('Y-m-d'))->setParameter('date2', date('Y-m-d'))
            ->orderBy('p.dateFrom', 'ASC')->orderBy('p.discount', 'ASC')
            ->getQuery()->getResult();

    }

    public function findCategoryPromotions()
    {

        return $qb2 = $this->createQueryBuilder('p')
            ->where('p.category IS NOT NULL')->select('p');
    }

    public function findProductPromotions()
    {

        return $qb2 = $this->createQueryBuilder('p')
            ->where('p.product IS NOT NULL')->select('p');
    }

    public function findUserPromotion()
    {
        return $qb2 = $this->createQueryBuilder('p')
            ->where('p.product IS NOT NULL')->andWhere('p.category IS NOT NULL')->select('p');

    }
}
