# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        ShopBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: ShopBundle:User
                property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                provider: our_db_provider
                check_path: our_login_check
                login_path: our_login

            logout:
                path: logout
                target: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
#    access_denied_url: /

    access_control:
                - { path: ^/register , roles: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/backstore , roles: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/product/ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/cart , roles: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/order , roles: IS_AUTHENTICATED_FULLY }
#                - { path: ^/ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
#                - { path: ^/ , roles: IS_AUTHENTICATED_ANONYMOUSLY }



                - { path: ^/order/profile, roles: [ ROLE_ADMIN, ROLE_SADMIN, ROLE_USER ,ROLE_EDIT] }
                - { path: ^/manage/product/edit, roles: [ ROLE_ADMIN, ROLE_SADMIN, ROLE_EDIT  ] }
                - { path: ^/manage/product/delete, roles: [ ROLE_ADMIN, ROLE_SADMIN, ROLE_EDIT  ] }
                - { path: ^/manage/category, roles: [ ROLE_ADMIN, ROLE_SADMIN, ROLE_EDIT  ] }

                - { path: ^/manage/promotion, roles: [ ROLE_ADMIN, ROLE_SADMIN, ROLE_EDIT ] }
                - { path: ^/manage/product, roles: [ ROLE_ADMIN, ROLE_SADMIN, ROLE_USER ,ROLE_EDIT] }
                - { path: ^/manage, roles: [ ROLE_ADMIN, ROLE_SADMIN ,ROLE_EDIT,ROLE_USER] }


